# Generated by Django 4.1.5 on 2023-01-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nombre')),
                ('author', models.CharField(max_length=64, verbose_name='Autor')),
                ('year', models.CharField(max_length=8, verbose_name='Año')),
                ('isbn', models.CharField(max_length=64, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
